//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::ingredient::Entity as Ingredient;
pub use super::recipe::Entity as Recipe;
pub use super::recipe_ingredient::Entity as RecipeIngredient;
